# DO: brew bundle cleanup

tap "leoafarias/fvm"

brew "neovim"
brew "tig"
brew "tmux"
brew "fish"
brew "peco"
brew "fzf"
brew "tree"
brew "mise"
brew "git-filter-repo"
brew "fvm" # instead of cask "flutter"
brew "libyaml"
brew "herdr"
brew "mint" # swift package manager
brew "gh"
brew "stripe"
# brew "imagemagick"

cask "hammerspoon"
cask "firefox"
cask "karabiner-elements"
cask "discord"
cask "figma"
cask "ghostty"
cask "slack"
cask "zed"

# cask "ngrok"
